spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: info
    com.wang: debug
  file: log/myblog-pro.log
server:
  port: 8081
