spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
logging:
  level:
    root: warn
    com.wang: debug
  file: log/myblog-dev.log
server:
  port: 8082